# Generated by Django 3.0.5 on 2021-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210507_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
